language: node_js
node_js: lts/*
cache:
  npm: true # This caches $HOME/.npm or node_modules, depending on the repository’s structure: 
# 1) This caches $HOME/.npm precisely when npm ci is the default script command. (See above.)
# 2) In all other cases, this will cache node_modules. Note that npm install will still run on every build and will update/install any new packages added to your package.json file

  
  yarn: true # This caches $HOME/.cache/yarn.
before_install:
  - npm install -g npm@latest
  - npm install -g expo-cli
install:
  - echo 'Installing the dependencies...'
  - npm install --non-interactive
  - expo diagnostics #  expo --version # expo-cli version
  - npm list expo # expo sdk version  
script:
  - echo 'Analysing app config...'
  - expo doctor --non-interactive
  - npm run test-ci || travis_terminate 1;
  - expo login -u ${EXPO_USERNAME} -p ${EXPO_PASSWORD}  
  - expo publish --non-interactive --quiet --release-channel default
notifications:
  email:
    recipients:
      - ${EMAIL_BORGO}
      - ${EMAIL_DANIELE}
    on_success: change  # options: [always|never|change] default: changes
    on_failure: always  # options: [always|never|change] default: always
