language: node_js
node_js:
  - lts/*
cache:
  npm: true
  yarn: true
  #directories: # don't need it, see https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
  #  - ~/.npm
before_install:
  - npm install -g npm@latest
  - npm install -g expo-cli
install:
  - echo 'Installing the dependencies...'
  - npm install --non-interactive
  - expo diagnostics #  expo --version # expo-cli version
  - npm list expo # expo sdk version  
script:
  - echo 'Analysing app config...'
  - expo doctor --non-interactive
  - npm run test-ci || travis_terminate 1;
  - expo login -u ${EXPO_USERNAME} -p ${EXPO_PASSWORD}  
  - expo publish --non-interactive --quiet --release-channel default
notifications:
  email:
    recipients:
      - ${EMAIL_BORGO}
      - ${EMAIL_DANIELE}
    on_success: change  # options: [always|never|change] default: changes
    on_failure: always  # options: [always|never|change] default: always
