language: node_js
node_js:
  - lts/*
cache:
  directories:
    - ~/.npm
before_script:
  - npm install -g npm@latest
  - npm install -g expo-cli
script:
  - echo 'Installing the dependencies...'
  - yarn install --non-interactive
  - yarn list expo # expo sdk version
  - expo diagnostics #  expo --version # expo-cli version
  - echo 'Analysing app config...'
  - expo doctor --non-interactive
  - npm run test
  - expo login -u ${EXPO_USERNAME} -p ${EXPO_PASSWORD}  
  - expo publish --non-interactive --quiet --release-channel default
notifications:
  email:
    recipients:
      - ${EMAIL_BORGO}
      - ${EMAIL_DANIELE}
    on_success: change  # options: [always|never|change] default: changes
    on_failure: always  # options: [always|never|change] default: always
