version: 2.1
# see https://circleci.com/blog/ci-for-react-apps/
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.7.0 
      # see https://circleci.com/developer/images/image/cimg/node
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@6"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Code style check
          command: npm run format-check
      - run:
          name: Run linter
          command: npm run lint                      