version: 2.1
# see https://circleci.com/blog/ci-for-react-apps/
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.7.0
      # https://github.com/CircleCI-Public/cimg-node
      # https://hub.docker.com/r/cimg/node
      # https://circleci.com/developer/images/image/cimg/node
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@6"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Code style check
          command: npm run format-check
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Testing
          command: npm run test-ci
      - run:
          name: Publish
          command: |
            npx expo-cli login -u ${EXPO_USERNAME} -p ${EXPO_PASSWORD}  
            npx expo-cli publish --non-interactive --quiet --release-channel default

#
#
# Visual Editor: https://circleci-public.github.io/visual-config-editor/
# References:
#   https://circleci.com/continuous-integration/
#   https://circleci.com/docs/configuration-reference
#   https://app.circleci.com/settings/user/notifications
#   https://circleci.com/docs/variables
# Immagini:
#   https://circleci.com/docs/circleci-images
#   https://github.com/circleci/circleci-images
#   https://circleci.com/developer/images
#   https://hub.docker.com/u/cimg
#   https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/
# Integrazioni:
#   https://circleci.com/docs/webhooks
#   https://circleci.com/blog/circleci-slack-integration/
#   https://circleci.com/blog/continuous-integration-slack-twilio/
# Orb Registry: https://circleci.com/developer/orbs
# Orbs:
#   https://github.com/woltsu/telegram-orb
#   https://circleci.com/developer/orbs/orb/woltsu/telegram
#   https://circleci.com/developer/orbs/orb/circleci/slack
#   https://github.com/CircleCI-Public/slack-orb/wiki
# Examples
#   https://github.com/CircleCI-Public/circleci-demo-react-native/blob/master/.circleci/config.yml
#   https://github.com/orgs/CircleCI-Public/repositories?type=all
#
# Languages
#   Java
#   Android
#     https://circleci.com/docs/language-android
#   JS
#     https://circleci.com/docs/language-javascript
# DB
#   https://circleci.com/docs/postgres-config#example-mysql-project
