version: 2.1
# see https://circleci.com/blog/ci-for-react-apps/
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.7.0 
      # see https://circleci.com/developer/images/image/cimg/node
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@6"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Code style check
          command: npm run format-check
      - run:
          name: Run linter
          command: npm run lint
#      - run:
#          name: Testing
#          command: npm run test-ci
      - run:
          name: Publish
          command: |
            sudo npm install --global expo-cli
            npx expo-cli login -u ${EXPO_USERNAME} -p ${EXPO_PASSWORD}  
            npx expo-cli publish --non-interactive --quiet --release-channel default
# see https://circleci.com/docs/configuration-reference#example
## https://circleci.com/docs/variables

##TODO:
#https://app.circleci.com/settings/user/notifications
#https://circleci.com/blog/circleci-slack-integration/
#https://github.com/CircleCI-Public/slack-orb/wiki
#https://circleci.com/developer/orbs/orb/circleci/slack
#https://circleci.com/blog/continuous-integration-slack-twilio/

## REF
#https://circleci.com/developer/orbs

